import tvsData from "@/../data/scrape/category-tvs.json";
import dvdBluRayData from "@/../data/scrape/dvd-blu-ray.json";
import soundbarsData from "@/../data/scrape/soundbars.json";
import speakersHifiData from "@/../data/scrape/speakers-hifi.json";
import tvAccessoriesData from "@/../data/scrape/tv-accessories.json";
import digitalSmartTvData from "@/../data/scrape/digital-smart-tv.json";
import headphonesData from "@/../data/scrape/headphones.json";

// ---- Enriched product data (scraped individual product pages) ----
// Combined index of all scraped product data, keyed by product ID.
// Generated by: node -e "..." (see scripts) or re-run after scraping.
// To regenerate: node scripts/build-products-index.js
import scrapedProductIndex from "@/../data/scrape/products-index.json";
import sizeVariantsData from "@/../data/scrape/size-variants.json";

/* eslint-disable @typescript-eslint/no-explicit-any */
const scrapedProductMap: Record<string, any> = scrapedProductIndex as any;
const sizeVariantsIndex: Record<string, any> = (sizeVariantsData as any).productToVariants || {};

// ---- Interfaces ----

export interface FlexpayOption {
  months: number;
  settleBy: string;
}

export interface Flexpay {
  monthlyAmount: number;
  months: number;
  totalPayable: number;
  apr: string;
  buyNowPayLater?: FlexpayOption[];
}

export interface WallBracketProduct {
  title: string;
  price: number;
  savings: number;
  separatePrice: number;
  image: string;
}

export interface WallBracket {
  text: string;
  product: WallBracketProduct;
}

export interface CareAndRepairPlan {
  plan: string;
  price: number;
  period: string;
  savings?: string;
  mostPopular?: boolean;
}

export interface EssentialService {
  name: string;
  price: number;
}

export interface CrossSellProduct {
  category: string;
  title: string;
  price: number;
  wasPrice?: number | null;
  savings?: number | null;
  rating?: number;
  reviewCount?: number;
  image: string;
  badge?: string;
}

export interface KeySpec {
  icon: string;
  label: string;
}

export interface SizeOption {
  size: string;
  selected: boolean;
  url: string;
}

export interface BadgeInfo {
  type: string;
  image: string;
}

export interface AwardInfo {
  name: string;
  image: string;
}

export interface ProductDescription {
  main: string;
  goodToKnow?: string[];
  features?: string[];
  additionalInformation?: string[];
  whyWeLoveIt?: { quote: string; author: string };
}

export interface BundleDeal {
  title: string;
  items: string[];
  totalPrice: number;
  savings: number;
}

export interface DeliveryInfo {
  freeDelivery: boolean;
  standardDeliveryPrice?: number;
  nextDayDeliveryPrice?: number;
  timeSlotDeliveryPrice?: number;
  nextDayTimeSlotPrice?: number;
  standardDeliveryDays?: number;
  collectionAvailable?: boolean;
  collectionTime?: string;
  collectionFree?: boolean;
}

export interface SizeVariant {
  size: string;
  productId: string;
  slug: string;
  price: number;
  selected: boolean;
}

export interface ProductDetail {
  // Core fields (always available from category JSON)
  name: string;
  brand: string;
  price: { current: number; was: number | null; savings: number | null };
  rating: { average: number; count: number };
  url: string;
  imageUrl: string | null;
  imageLarge: string | null;
  specs: string[];
  badges: string[];
  offers: string[];
  deliveryFree: boolean;
  energyRating?: string | null;
  category: string;
  categorySlug: string;
  productId?: string;

  // Enriched fields (available when scraped product JSON exists)
  images?: {
    gallery: string[];
    thumbnails: string[];
    video?: string;
  };
  keySpecs?: KeySpec[];
  sizeOptions?: SizeOption[];
  flexpay?: Flexpay;
  wallBracket?: WallBracket;
  careAndRepair?: CareAndRepairPlan[];
  careAndRepairBenefits?: string[];
  essentialServices?: EssentialService[];
  crossSellProducts?: CrossSellProduct[];
  badgeImages?: BadgeInfo[];
  awards?: AwardInfo[];
  specifications?: Record<string, Record<string, string>>;
  description?: ProductDescription;
  deliveryInfo?: DeliveryInfo;
  bundleDeals?: BundleDeal[];
  promotionalOffers?: Array<{ title: string; description: string; code?: string; terms?: string }>;
  whatsInTheBox?: string[];
  modelNumber?: string;
}

// ---- Category data mapping ----

const allCategories: { data: any; name: string; slug: string }[] = [
  { data: tvsData, name: "TVs", slug: "televisions/tvs" },
  { data: dvdBluRayData, name: "DVD, Blu-ray & Home Cinema", slug: "dvd-blu-ray-and-home-cinema" },
  { data: soundbarsData, name: "Sound Bars", slug: "dvd-blu-ray-and-home-cinema/home-cinema-systems-and-soundbars/sound-bars" },
  { data: speakersHifiData, name: "HiFi & Speakers", slug: "speakers-and-hi-fi-systems" },
  { data: tvAccessoriesData, name: "TV Accessories", slug: "tv-accessories" },
  { data: digitalSmartTvData, name: "Digital & Smart TV", slug: "digital-and-smart-tv" },
  { data: headphonesData, name: "Headphones", slug: "headphones/headphones" },
];

function toLargeImage(imageUrl: string | null): string | null {
  if (!imageUrl) return null;
  return imageUrl
    .replace("?$g-small$&fmt=auto", "?fmt=auto")
    .replace("?$s-swatch$&fmt=auto", "?fmt=auto")
    .replace("$g-small$", "$l-large$")
    .replace("$s-swatch$", "$l-large$");
}

function extractProductId(slug: string): string | undefined {
  const match = slug.match(/(\d{6,})\.html$/);
  return match ? match[1] : undefined;
}

function mergeScrapedData(base: ProductDetail, scraped: any): ProductDetail {
  // Merge scraped data into the base product
  const merged = { ...base };

  // Images
  if (scraped.images?.gallery?.length > 0) {
    merged.images = {
      gallery: scraped.images.gallery,
      thumbnails: scraped.images.thumbnails || [],
      video: scraped.images.video || undefined,
    };
  }

  // Key specs
  if (scraped.keySpecs?.length > 0) {
    merged.keySpecs = scraped.keySpecs;
  }

  // Size options
  if (scraped.sizeOptions?.length > 0) {
    merged.sizeOptions = scraped.sizeOptions;
  }

  // Energy rating from scraped data (more detailed)
  if (scraped.energyRating?.class) {
    merged.energyRating = scraped.energyRating.class;
  }

  // Flexpay
  if (scraped.flexpay?.monthlyAmount) {
    merged.flexpay = scraped.flexpay;
  }

  // Wall bracket
  if (scraped.wallBracket?.product?.title) {
    merged.wallBracket = scraped.wallBracket;
  }

  // Care and repair
  if (scraped.careAndRepair?.length > 0) {
    merged.careAndRepair = scraped.careAndRepair;
  }
  if (scraped.careAndRepairBenefits?.length > 0) {
    merged.careAndRepairBenefits = scraped.careAndRepairBenefits;
  }

  // Essential services
  if (scraped.essentialServices?.length > 0) {
    merged.essentialServices = scraped.essentialServices;
  }

  // Cross-sell products
  if (scraped.crossSellProducts?.length > 0) {
    merged.crossSellProducts = scraped.crossSellProducts;
  }

  // Offers (prefer scraped if more detailed)
  if (scraped.offers?.length > 0) {
    merged.offers = scraped.offers;
  }

  // Badge images
  if (scraped.badges?.length > 0) {
    merged.badgeImages = scraped.badges;
  }

  // Awards
  if (scraped.awards?.length > 0) {
    merged.awards = scraped.awards;
  }

  // Specifications
  if (scraped.specifications && Object.keys(scraped.specifications).length > 0) {
    merged.specifications = scraped.specifications;
  }

  // Description
  if (scraped.description?.main) {
    merged.description = scraped.description;
  }

  // Delivery info
  if (scraped.deliveryInfo) {
    merged.deliveryInfo = scraped.deliveryInfo;
  }

  // Bundle deals
  if (scraped.bundleDeals?.length > 0) {
    merged.bundleDeals = scraped.bundleDeals;
  }

  // Promotional offers
  if (scraped.promotionalOffers?.length > 0) {
    merged.promotionalOffers = scraped.promotionalOffers;
  }

  // What's in the box
  if (scraped.whatsInTheBox?.length > 0) {
    merged.whatsInTheBox = scraped.whatsInTheBox;
  }

  // Model number
  if (scraped.modelNumber) {
    merged.modelNumber = scraped.modelNumber;
  }

  // Override price from scraped if available (more up-to-date)
  if (scraped.price?.current) {
    merged.price = {
      current: scraped.price.current,
      was: scraped.price.was ?? merged.price.was,
      savings: scraped.price.savings ?? merged.price.savings,
    };
  }

  // Override rating from scraped if available
  if (scraped.rating?.average) {
    merged.rating = {
      average: scraped.rating.average,
      count: scraped.rating.count ?? merged.rating.count,
    };
  }

  return merged;
}

export function getProductBySlug(slug: string): ProductDetail | null {
  const targetPath = `/products/${slug}`;
  const productId = extractProductId(slug);

  for (const cat of allCategories) {
    const products = cat.data.products || [];
    for (const p of products) {
      const productUrl = (p.url || p.productUrl || "")
        .replace("https://www.currys.co.uk", "");

      if (productUrl === targetPath) {
        const base: ProductDetail = {
          name: p.name || p.title || "",
          brand: p.brand || "",
          price: {
            current: p.price?.current ?? (typeof p.price === "number" ? p.price : 0),
            was: p.price?.was ?? p.wasPrice ?? null,
            savings: p.price?.savings ?? p.savings ?? null,
          },
          rating: {
            average: p.rating?.average ?? (typeof p.rating === "number" ? p.rating : 0),
            count: p.rating?.count ?? p.reviewCount ?? 0,
          },
          url: productUrl,
          imageUrl: p.imageUrl || null,
          imageLarge: toLargeImage(p.imageUrl),
          specs: p.specs || [],
          badges: p.badges || [],
          offers: p.offers || [],
          deliveryFree: p.deliveryFree ?? true,
          energyRating: p.energyRating || null,
          category: cat.name,
          categorySlug: cat.slug,
          productId,
        };

        // Try to merge with scraped product data
        if (productId && scrapedProductMap[productId]) {
          return mergeScrapedData(base, scrapedProductMap[productId]);
        }

        // Fallback: generate gallery images from CDN pattern
        if (productId) {
          const cdnBase = `https://media.currys.biz/i/currysprod/${productId}`;
          base.images = {
            gallery: [
              `${cdnBase}?$l-large$&fmt=auto`,
              ...Array.from({ length: 6 }, (_, i) =>
                `${cdnBase}_${String(i).padStart(3, "0")}?$l-large$&fmt=auto`
              ),
            ],
            thumbnails: [
              `${cdnBase}?$t-thumbnail$&fmt=auto`,
              ...Array.from({ length: 6 }, (_, i) =>
                `${cdnBase}_${String(i).padStart(3, "0")}?$t-thumbnail$&fmt=auto`
              ),
            ],
          };
        }

        return base;
      }
    }
  }

  return null;
}

export function getAllProducts(): ProductDetail[] {
  const products: ProductDetail[] = [];
  for (const cat of allCategories) {
    const items = cat.data.products || [];
    for (const p of items) {
      const productUrl = (p.url || p.productUrl || "")
        .replace("https://www.currys.co.uk", "");
      products.push({
        name: p.name || p.title || "",
        brand: p.brand || "",
        price: {
          current: p.price?.current ?? (typeof p.price === "number" ? p.price : 0),
          was: p.price?.was ?? p.wasPrice ?? null,
          savings: p.price?.savings ?? p.savings ?? null,
        },
        rating: {
          average: p.rating?.average ?? (typeof p.rating === "number" ? p.rating : 0),
          count: p.rating?.count ?? p.reviewCount ?? 0,
        },
        url: productUrl,
        imageUrl: p.imageUrl || null,
        imageLarge: toLargeImage(p.imageUrl),
        specs: p.specs || [],
        badges: p.badges || [],
        offers: p.offers || [],
        deliveryFree: p.deliveryFree ?? true,
        energyRating: p.energyRating || null,
        category: cat.name,
        categorySlug: cat.slug,
      });
    }
  }
  return products;
}

/**
 * Get size variants for a product.
 * Returns an array of SizeVariant objects for all sizes of the same model,
 * with the current product marked as `selected: true`.
 * Falls back to the product's own sizeOptions (without URLs) if no variant mapping exists.
 */
export function getSizeVariants(productId: string): SizeVariant[] {
  // Check the size variants mapping first
  const variants = sizeVariantsIndex[productId];
  if (variants && Array.isArray(variants) && variants.length > 0) {
    return variants.map((v: any) => ({
      size: v.size,
      productId: v.productId,
      slug: v.slug || "",
      price: v.price || 0,
      selected: v.productId === productId,
    }));
  }

  return [];
}
/* eslint-enable @typescript-eslint/no-explicit-any */
