import { stripDomain } from "@/lib/constants";
import tvsData from "@/../data/scrape/category-tvs.json";
import dvdBluRayData from "@/../data/scrape/dvd-blu-ray.json";
import soundbarsData from "@/../data/scrape/soundbars.json";
import speakersHifiData from "@/../data/scrape/speakers-hifi.json";
import tvAccessoriesData from "@/../data/scrape/tv-accessories.json";
import digitalSmartTvData from "@/../data/scrape/digital-smart-tv.json";
import headphonesData from "@/../data/scrape/headphones.json";
import tvWallBracketsData from "@/../data/scrape/tv-wall-brackets.json";
import cablesAccessoriesData from "@/../data/scrape/cables-accessories.json";
import remoteControlsData from "@/../data/scrape/remote-controls.json";
import tvAerialsData from "@/../data/scrape/tv-aerials.json";
import radiosData from "@/../data/scrape/radios.json";
import bluRayDvdPlayersData from "@/../data/scrape/blu-ray-dvd-players.json";
import homeCinemaSystemsData from "@/../data/scrape/home-cinema-systems.json";
import { toLocalImage, getListingImage, getGalleryImages, getThumbnailImages, getImageSortKey } from "./images";

// ---- Enriched product data (scraped individual product pages) ----
// Combined index of all scraped product data, keyed by product ID.
// Generated by: node -e "..." (see scripts) or re-run after scraping.
// To regenerate: node scripts/build-products-index.js
import scrapedProductIndex from "@/../data/scrape/products-index.json";
import sizeVariantsData from "@/../data/scrape/size-variants.json";

/* eslint-disable @typescript-eslint/no-explicit-any */
const scrapedProductMap: Record<string, any> = scrapedProductIndex as any;
const sizeVariantsIndex: Record<string, any> = (sizeVariantsData as any).productToVariants || {};

// ---- Interfaces ----

export interface WallBracketProduct {
  title: string;
  price: number;
  savings: number;
  separatePrice: number;
  image: string;
}

export interface WallBracket {
  text: string;
  product: WallBracketProduct;
}

export interface CareAndRepairPlan {
  plan: string;
  price: number;
  period: string;
  savings?: string;
  mostPopular?: boolean;
}

export interface EssentialService {
  name: string;
  price: number;
}

export interface CrossSellProduct {
  category: string;
  title: string;
  price: number;
  wasPrice?: number | null;
  savings?: number | null;
  rating?: number;
  reviewCount?: number;
  image: string;
  badge?: string;
}

export interface KeySpec {
  icon: string;
  label: string;
}

export interface SizeOption {
  size: string;
  selected: boolean;
  url: string;
}

export interface BadgeInfo {
  type: string;
  image: string;
}

export interface AwardInfo {
  name: string;
  image: string;
}

export interface ProductDescription {
  main: string;
  goodToKnow?: string[];
  features?: string[];
  additionalInformation?: string[];
  whyWeLoveIt?: { quote: string; author: string };
}

export interface BundleDeal {
  title: string;
  items: string[];
  totalPrice: number;
  savings: number;
}

export interface DeliveryInfo {
  freeDelivery: boolean;
  standardDeliveryPrice?: number;
  nextDayDeliveryPrice?: number;
  timeSlotDeliveryPrice?: number;
  nextDayTimeSlotPrice?: number;
  standardDeliveryDays?: number;
}

export interface SizeVariant {
  size: string;
  productId: string;
  slug: string;
  price: number;
  selected: boolean;
  available: boolean;
}

export interface ProductDetail {
  // Core fields (always available from category JSON)
  name: string;
  brand: string;
  price: { current: number; was: number | null; savings: number | null };
  rating: { average: number; count: number };
  url: string;
  imageUrl: string | null;
  imageLarge: string | null;
  specs: string[];
  badges: string[];
  offers: string[];
  deliveryFree: boolean;
  energyRating?: string | null;
  energyLabelUrl?: string | null;
  category: string;
  categorySlug: string;
  productId?: string;

  // Enriched fields (available when scraped product JSON exists)
  images?: {
    gallery: string[];
    thumbnails: string[];
    video?: string;
  };
  keySpecs?: KeySpec[];
  sizeOptions?: SizeOption[];
  wallBracket?: WallBracket;
  careAndRepair?: CareAndRepairPlan[];
  careAndRepairBenefits?: string[];
  essentialServices?: EssentialService[];
  crossSellProducts?: CrossSellProduct[];
  badgeImages?: BadgeInfo[];
  awards?: AwardInfo[];
  specifications?: Record<string, Record<string, string>>;
  description?: ProductDescription;
  deliveryInfo?: DeliveryInfo;
  bundleDeals?: BundleDeal[];
  promotionalOffers?: Array<{ title: string; description: string; code?: string; terms?: string }>;
  whatsInTheBox?: string[];
  modelNumber?: string;
}

// ---- Category data mapping ----

const allCategories: { data: any; name: string; slug: string }[] = [
  { data: tvsData, name: "Televisions", slug: "televisions/tvs" },
  { data: dvdBluRayData, name: "DVD, Blu-ray & Home Cinema", slug: "dvd-blu-ray-and-home-cinema" },
  { data: soundbarsData, name: "Sound Bars", slug: "dvd-blu-ray-and-home-cinema/home-cinema-systems-and-soundbars/sound-bars" },
  { data: speakersHifiData, name: "HiFi & Speakers", slug: "speakers-and-hi-fi-systems" },
  { data: tvAccessoriesData, name: "TV Accessories", slug: "tv-accessories" },
  { data: digitalSmartTvData, name: "Digital & Smart TV", slug: "digital-and-smart-tv" },
  { data: headphonesData, name: "Headphones", slug: "headphones/headphones" },
  { data: tvWallBracketsData, name: "TV Wall Brackets", slug: "tv-accessories/tv-wall-brackets-and-stands/tv-wall-brackets" },
  { data: cablesAccessoriesData, name: "Cables & Accessories", slug: "tv-accessories/cables-and-accessories" },
  { data: remoteControlsData, name: "Remote Controls", slug: "tv-accessories/remote-controls" },
  { data: tvAerialsData, name: "TV Aerials", slug: "tv-accessories/tv-aerials" },
  { data: radiosData, name: "Radios", slug: "radios" },
  { data: bluRayDvdPlayersData, name: "Blu-ray & DVD Players", slug: "dvd-blu-ray-and-home-cinema/blu-ray-and-dvd-players" },
  { data: homeCinemaSystemsData, name: "Home Cinema Systems", slug: "dvd-blu-ray-and-home-cinema/home-cinema-systems-and-soundbars/home-cinema-systems" },
];

function toLargeImage(imageUrl: string | null, productId?: string): string | null {
  if (productId) return `/images/products/${productId}/large.webp`;
  if (!imageUrl) return null;
  return toLocalImage(imageUrl
    .replace("?$g-small$&fmt=auto", "?$l-large$&fmt=auto")
    .replace("?$s-swatch$&fmt=auto", "?$l-large$&fmt=auto")
    .replace("$g-small$", "$l-large$")
    .replace("$s-swatch$", "$l-large$"));
}

function extractProductId(slug: string): string | undefined {
  const match = slug.match(/(\d{6,})(?:\.html)?$/);
  return match ? match[1] : undefined;
}

function mergeScrapedData(base: ProductDetail, scraped: any): ProductDetail {
  // Merge scraped data into the base product
  const merged = { ...base };

  // Images - sort by suffix for correct order, then convert CDN URLs to local paths
  if (scraped.images?.gallery?.length > 0) {
    const sortedGallery = [...scraped.images.gallery].sort(
      (a: string, b: string) => getImageSortKey(a) - getImageSortKey(b)
    );
    const sortedThumbs = [...(scraped.images.thumbnails || [])].sort(
      (a: string, b: string) => getImageSortKey(a) - getImageSortKey(b)
    );
    merged.images = {
      gallery: sortedGallery.map((url: string) => toLocalImage(url)).filter(Boolean),
      thumbnails: sortedThumbs.map((url: string) => toLocalImage(url)).filter(Boolean),
      video: scraped.images.video || undefined,
    };
  }

  // Key specs
  if (scraped.keySpecs?.length > 0) {
    merged.keySpecs = scraped.keySpecs;
  }

  // Size options
  if (scraped.sizeOptions?.length > 0) {
    merged.sizeOptions = scraped.sizeOptions;
  }

  // Energy rating from scraped data (more detailed)
  if (scraped.energyRating?.class) {
    merged.energyRating = scraped.energyRating.class;
  }
  if (scraped.energyRating?.labelUrl) {
    merged.energyLabelUrl = scraped.energyRating.labelUrl;
  }

  // Wall bracket
  if (scraped.wallBracket?.product?.title) {
    merged.wallBracket = scraped.wallBracket;
  }

  // Care and repair
  if (scraped.careAndRepair?.length > 0) {
    merged.careAndRepair = scraped.careAndRepair;
  }
  if (scraped.careAndRepairBenefits?.length > 0) {
    merged.careAndRepairBenefits = scraped.careAndRepairBenefits;
  }

  // Essential services
  if (scraped.essentialServices?.length > 0) {
    merged.essentialServices = scraped.essentialServices;
  }

  // Cross-sell products — normalize image paths and coerce old sparse format
  if (scraped.crossSellProducts?.length > 0) {
    merged.crossSellProducts = scraped.crossSellProducts.map((item: any) => ({
      category: item.category || "Accessories",
      title: item.title || item.name || "",
      price: typeof item.price === "number" ? item.price : 0,
      wasPrice: item.wasPrice ?? null,
      savings: item.savings ?? null,
      rating: item.rating ?? undefined,
      reviewCount: item.reviewCount ?? undefined,
      image: item.image?.startsWith("/images/") ? item.image : toLocalImage(item.image || ""),
      badge: item.badge || undefined,
    }));
  }

  // Offers (prefer scraped if more detailed)
  if (scraped.offers?.length > 0) {
    merged.offers = scraped.offers;
  }

  // Badge images
  if (scraped.badges?.length > 0) {
    merged.badgeImages = scraped.badges;
  }

  // Awards
  if (scraped.awards?.length > 0) {
    merged.awards = scraped.awards;
  }

  // Specifications
  if (scraped.specifications && Object.keys(scraped.specifications).length > 0) {
    merged.specifications = scraped.specifications;
  }

  // Description
  if (scraped.description?.main) {
    merged.description = scraped.description;
  }

  // Delivery info
  if (scraped.deliveryInfo) {
    merged.deliveryInfo = scraped.deliveryInfo;
  }

  // Bundle deals
  if (scraped.bundleDeals?.length > 0) {
    merged.bundleDeals = scraped.bundleDeals;
  }

  // Promotional offers
  if (scraped.promotionalOffers?.length > 0) {
    merged.promotionalOffers = scraped.promotionalOffers;
  }

  // What's in the box
  if (scraped.whatsInTheBox?.length > 0) {
    merged.whatsInTheBox = scraped.whatsInTheBox;
  }

  // Model number
  if (scraped.modelNumber) {
    merged.modelNumber = scraped.modelNumber;
  }

  // Override price from scraped if available (more up-to-date)
  if (scraped.price?.current) {
    merged.price = {
      current: scraped.price.current,
      was: scraped.price.was ?? merged.price.was,
      savings: scraped.price.savings ?? merged.price.savings,
    };
  }

  // Override rating from scraped if available
  if (scraped.rating?.average) {
    merged.rating = {
      average: scraped.rating.average,
      count: scraped.rating.count ?? merged.rating.count,
    };
  }

  return merged;
}

/**
 * Look up a product by its URL slug (e.g., "samsung-qe65qn85d-65-smart-4k-neo-qled-tv-10282094.html").
 *
 * Searches all 14 category data files for a product whose URL matches `/products/${slug}`.
 * Note: This matches by full URL slug, NOT by bare product ID.
 *
 * If found, merges category-level data with any individually scraped product data
 * from `products-index.json` (gallery images, specifications, care plans, etc.).
 *
 * @returns ProductDetail or null if no product matches the slug.
 */
export function getProductBySlug(slug: string): ProductDetail | null {
  const targetPath = `/products/${slug}`;
  const productId = extractProductId(slug);

  for (const cat of allCategories) {
    const products = cat.data.products || [];
    for (const p of products) {
      const productUrl = stripDomain(p.url || p.productUrl || "");

      if (productUrl === targetPath || productUrl === targetPath + ".html") {
        const base: ProductDetail = {
          name: p.name || p.title || "",
          brand: p.brand || "",
          price: {
            current: p.price?.current ?? (typeof p.price === "number" ? p.price : 0),
            was: p.price?.was ?? p.wasPrice ?? null,
            savings: p.price?.savings ?? p.savings ?? null,
          },
          rating: {
            average: p.rating?.average ?? (typeof p.rating === "number" ? p.rating : 0),
            count: p.rating?.count ?? p.reviewCount ?? 0,
          },
          url: productUrl,
          imageUrl: productId ? getListingImage(productId) : (p.imageUrl || null),
          imageLarge: toLargeImage(p.imageUrl, productId),
          specs: p.specs || [],
          badges: p.badges || [],
          offers: p.offers || [],
          deliveryFree: p.deliveryFree ?? true,
          energyRating: p.energyRating || null,
          energyLabelUrl: null,
          category: cat.name,
          categorySlug: cat.slug,
          productId,
        };

        // Try to merge with scraped product data
        if (productId && scrapedProductMap[productId]) {
          return mergeScrapedData(base, scrapedProductMap[productId]);
        }

        // Generate gallery images using local paths
        if (productId) {
          base.images = {
            gallery: getGalleryImages(productId),
            thumbnails: getThumbnailImages(productId),
          };
        }

        return base;
      }
    }
  }

  return null;
}

/**
 * Get all products from all 14 categories as ProductDetail objects.
 * Used by the search index to build a searchable product list.
 * Returns category-level data only (no scraped enrichment) for performance.
 */
export function getAllProducts(): ProductDetail[] {
  const products: ProductDetail[] = [];
  for (const cat of allCategories) {
    const items = cat.data.products || [];
    for (const p of items) {
      const productUrl = stripDomain(p.url || p.productUrl || "");
      const pid = p.productId || extractProductId(productUrl.replace("/products/", "") + ".html");
      products.push({
        name: p.name || p.title || "",
        brand: p.brand || "",
        price: {
          current: p.price?.current ?? (typeof p.price === "number" ? p.price : 0),
          was: p.price?.was ?? p.wasPrice ?? null,
          savings: p.price?.savings ?? p.savings ?? null,
        },
        rating: {
          average: p.rating?.average ?? (typeof p.rating === "number" ? p.rating : 0),
          count: p.rating?.count ?? p.reviewCount ?? 0,
        },
        url: productUrl,
        imageUrl: pid ? getListingImage(pid) : (p.imageUrl || null),
        imageLarge: toLargeImage(p.imageUrl, pid),
        specs: p.specs || [],
        badges: p.badges || [],
        offers: p.offers || [],
        deliveryFree: p.deliveryFree ?? true,
        energyRating: p.energyRating || null,
        energyLabelUrl: null,
        category: cat.name,
        categorySlug: cat.slug,
        productId: pid,
      });
    }
  }
  return products;
}


/**
 * Get size variants for a product.
 * Returns an array of SizeVariant objects for all sizes of the same model,
 * with the current product marked as `selected: true`.
 * Falls back to the product's own sizeOptions (without URLs) if no variant mapping exists.
 */
export function getSizeVariants(productId: string): SizeVariant[] {
  // Check the size variants mapping first
  const variants = sizeVariantsIndex[productId];
  if (variants && Array.isArray(variants) && variants.length > 0) {
    return variants.map((v: any) => ({
      size: v.size,
      productId: v.productId,
      slug: v.slug || "",
      price: v.price || 0,
      selected: v.productId === productId,
      available: v.available ?? Boolean(v.slug && v.productId),
    }));
  }

  return [];
}
/* eslint-enable @typescript-eslint/no-explicit-any */
